from calorine.caro.tests.historyentry import HistoryEntryTests
from calorine.caro.tests.playlistentry import PlaylistEntryTests
from calorine.caro.tests.logs import LogsTests
from calorine.caro.tests.vote import VoteTests
from calorine.caro.tests.song import SongTests
from calorine.caro.tests.stream import StreamTests
from calorine.caro.tests.cache import CachesTests
from calorine.caro.tests.command import CommandTests
from calorine.caro.tests.context_processors import ContextProcessorsTests
from calorine.caro.tests.search import SearchTests
from calorine.caro.tests.utils import UtilsTests
from calorine.caro.tests.urls import UrlsTests
from calorine.caro.tests.profile import ProfileTests
